version: "3.9"
services:
  hermes:
    image: informalsystems/hermes:0.13.0
    volumes:
      - "hermes-home:/home/hermes"
      - ".:/config:ro"
    command:
      - -c
      - /config/hermes.config
      - start
volumes:
  hermes-home:
    external: true
