version: "3.9"
services:
  hermes:
    network_mode: host
    build:
      context: .
      dockerfile: hermes.Dockerfile
      args:
        TAG: hu55a1n1/1793-begin-end-block-chan-events
    image: hermes:0.11.0
    volumes:
      - "hermes-home:/home/hermes"
      - ".:/config:ro"
    command:
      - -c
      - /config/hermes.config
      - start
volumes:
  hermes-home:
    external: true
