version: "3.9"
services:
  hermes:
    network_mode: host
    build:
      context: .
      dockerfile: hermes.Dockerfile
      args:
        TAG: d082feae2c1a9925ec24fd4654d098eca91980e0 # romac/1837-non-standard-port
    image: hermes:0.12.0-pre
    volumes:
      - "hermes-home:/home/hermes"
      - ".:/config:ro"
    command:
      - -c
      - /config/hermes.config
      - start
volumes:
  hermes-home:
    external: true
